language: java
dist: trusty
jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk6
cache:
  directories:
  - .autoconf
  - $HOME/.m2
script:
- mvn -Dmaven.javadoc.skip=true package
#- mvn test -B # default
#before_deploy: "echo 'ready?'"
deploy:
  provider: releases
  api_key:
    secure: MOZgBA6s8YN5Lod4v4OEJmKl6w7w+H9VUQw8kdBIJ2nPcW8j7hrzQSnqeS4cX9EhQWIkqnuDEwWCs8SKIBg93O4NkGSjS/uvUZqFa9Cq4bU3LeiekS
JFLjNpHTxm4nqcjyUw8uFzjQpMXDdGC8a8+wusu9X78ENnGYW6NqEly+Au4UyIXFs9l/Drab6nb7Q372p6cjW3S0EZSsaBqvgI4JUdKX2FiWfK6sAbf55kKlxGRtN7
muOJVU5KeDfv1r7M0Uywc8MekO5CWrjHPomhlqb3g4I3JW59jgIwo6pGiBsePecyTkJRc5jcYw4xLfPd4hZcY4O30+pCyJhdVnB0sIS4vMjQL4Cv7tyq2yucEjHVPL
qjNeD5I+2eEiD+6SC+NT68qITiIxOnJtPkEJEKBCZFUBJYnY70qIuAOh52AZmTwKFMlunFxlcD9mY1T7w+nqQTIYR73d27KgK4dtaPWKONwphGlcN+mkwE04t1S1zg
fmjYCky096K2GmSoJWsikHvv5mJKaj8luoj/gX6uMY+1OsoZdmQ/YDswIv0t1iOYNg+t1wRA3U+wK+7sQI2V3FwXCM2zreWUNEBlsk72ODLpdzZ6EtC6jyOvwUPl1z
Ytsq2M9Kx2v5fULd6zUX8phcZAG1iUBys0gWpOBMY2YnZxKXyQf3Eeddx3EwsX5yQ=
#  api_key: "GITHUB OAUTH TOKEN"
  file: "/home/travis/build/ReSearchITEng/kubernetes-plugin/target/kubernetes.hpi"
#  file_glob: true
#  file: directory/*
  skip_cleanup: true
  overwrite: true
#  on:
#    repo: ReSearchITEng/kubernetes-plugin
#    tags: true
#    all_branches: false
#    branch: master
#after_deploy:
#  - ./after_deploy_1.sh
#
